# Generated by Django 4.2 on 2023-05-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_dt', 'post', 'author'), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_dt', 'author'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
